### ISSUE TITLE
Jobs show up as "legacy" in Eagle 9.x

### ISSUE THREAD

**Issue by someburner** [OSHPark/OSHPark-Eagle-Tools#6]
Using "cam-7.2+" files in Eagle 9.4.2, the jobs show up under a Legacy section and Eagle prompts asking whether you want to convert to new CAM format.

![image](https://user-images.githubusercontent.com/9430255/64981581-37c3e580-d871-11e9-9a17-54c6ec86de5d.png)

Is it recommended to convert them to the new format or use as-is? It would be nice to have 9.x compatible cams.

**Comment by tekdemo** [comment]
We actually ship a non-legacy cam inside Eagle under Load > Templates > Third Party > OSH Park, so conversion isn't needed for the newer CAM features. 

The Legacy format still works with 9.2, and just uses an older CAM engine. The reason we've kept the "Legacy" CAM is due to a number of output bugs in the newer 9.x CAM engine, and the Legacy setup was a robust and reliable way to ensure customers can generate output that works. We're currently revisiting this, now that things with the new CAM have settled down a bit, and most of the problematic versions have been upgraded on people's systems.

**Comment by someburner** [comment]
Thanks!
